version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - leagues-db:/var/lib/postgresql/data
    
  api:
    restart: always
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules # To keep the node_modules/ folter installed in the image -> creates a new volume each time
    command: sh ./start-script.sh

volumes:
  leagues-db:
