version: "3.8"

services:
  db:
    image: postgres
    # container_name: 'test-db-container'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
